# Generated by Django 4.0.3 on 2022-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('mfd_dt', models.DateField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
